AY2425S2-CS2103T-T15-3/tp

docs/DeveloperGuide.md
=> Update target user profile and value proposition

src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/logic/commands/RemoveTagCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/commands/RemoveTagCommandTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Fix merge issues and most test cases

src/main/java/seedu/address/logic/commands/AttendanceCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/attendance/Attendance.java, src/main/java/seedu/address/model/person/Nric.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/storage/JsonAdaptedAttendance.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java
**_Main Addition_**
Added Attendance class which stores the attendance details for a person in the address book, including information such as the total number of working days so far in that year, the number of absent days for the person, and the calculated attendance rate for the person.
Added parseAttendance method in ParserUtil class which breaks down one whole string of multiple NRICs into List<String> nricList.
Added AttendanceCommandParser class with a parse method that makes use of the above parseAttendance method in ParserUtil class to attain the parameters needed to instantiate an AttendanceCommand class
Added AttendanceCommand class that marks attendance for all persons in the address book, treating the provided NRICs after "/absent" as absentees. Then, it increments the global …
=> Implement AttendanceCommand

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/person/comparators/AddressComparator.java, src/main/java/seedu/address/model/person/comparators/EmailComparator.java, src/main/java/seedu/address/model/person/comparators/HireComparator.java, src/main/java/seedu/address/model/person/comparators/NameComparator.java, src/main/java/seedu/address/model/person/comparators/NricComparator.java, src/main/java/seedu/address/model/person/comparators/PhoneComparator.java
- Added and Implemented a new command: sort
- Added a new package "comparators" under seedu.address.model.person
closes #63
=> Branch sort command

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/main/java/seedu/address/model/person/comparators/NricComparator.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/SortCommandParserTest.java, src/test/java/seedu/address/model/person/comparators/AddressComparatorTest.java, src/test/java/seedu/address/model/person/comparators/EmailComparatorTest.java, src/test/java/seedu/address/model/person/comparators/HireComparatorTest.java, src/test/java/seedu/address/model/person/comparators/NameComparatorTest.java, src/test/java/seedu/address/model/person/comparators/NricComparatorTest.java, src/test/java/seedu/address/model/person/comparators/PhoneComparatorTest.java
Wrote testcases for:
- SortCommand
- SortCommandParser
- all comparators in seedu.address.model.person.comparators
=> Branch testcases sort

docs/diagrams/BetterModelClassDiagram.puml
Make changes to BetterModelClassDiagram.puml
=> Edit UML Diagram

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/LeaveCommand.java, src/main/java/seedu/address/logic/commands/RemoveTagCommand.java, src/main/java/seedu/address/logic/parser/LeaveCommandParser.java, src/test/java/seedu/address/logic/commands/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/LeaveCommandTest.java, src/test/java/seedu/address/logic/parser/LeaveCommandParserTest.java, src/test/java/seedu/address/model/leave/LeaveTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
- Updated Leave, Edit, AddTag and RemoveTag to trigger Ui changes in PersonDetailsPanel
- Updated associated test cases
- Added new test cases for Leave Management
- Added missing newline at EOF in UserGuide.md which was causing CI to fail
=> Trigger UI updates after commands and add test cases for leave management

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Hire.java
Bugs fixed:
- Invalid Hire now shows Hire.MESSAGE_CONSTRAINTS instead of Email.MESSAGE_CONSTRAINTS
- LocalDate is now used to verify valid hire date
closes #84
=> Fix bugs related to Hire class

src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Changes made:
- isSamePerson method in Person.java now looks at NRIC when considering duplicate
- Resolved duplicate NRIC in TypicalPersons.java
closes #90
This change closes #89 as well since the add command checks for model.hasPerson which uses the isSamePerson method
=> Fix duplicate NRIC issue

src/main/java/seedu/address/ui/HelpWindow.java
Now provides correct link to our user guide (closes #92)
=> Update HelpWindow url

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AttendanceCommand.java
Will do a second update on tags, whether ,.`- are allowed, whether NRICs should allow lowercase, whether more alphabets should be allowed as start of NRIC
=> Add more details and specifications to our available commands on UG

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/RemoveTagCommand.java
Fix error message for removetag command.
=> Branch alphatestv2.0

README.md, docs/DeveloperGuide.md, docs/index.md
=> Update developer guide links, project name and badges

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java
Added comprehensive error catching for edit command
Added detail for edit command in User Guide
=> Added comprehensive error catching

src/main/java/seedu/address/logic/commands/EditCommand.java
=> Branch fix edit bug 2

src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/ui/PersonDetailsPanel.java, src/main/resources/view/LightTheme.css, src/main/resources/view/ResultDisplay.fxml
Used about 30-40 lines of code to fix a few High severity functionality bugs.
=> Functionality bugfixing - Tag character count, attendance term, scrollbar for results

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java
=> Fix "Error message for duplicate NRIC not specific enough"

src/main/java/seedu/address/logic/parser/LeaveCommandParser.java, src/main/java/seedu/address/model/leave/Leave.java
Changes made
- Fixed error message when index is invalid (closes #129)
- Update max year for `Leave` class to 2099
=> Fix bugs related to Leave

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/model/leave/Leave.java, src/main/java/seedu/address/model/person/Hire.java
Edit user stories to fit the context of our application.
Edit the format needed for dates in user guide.
=> Branch v1.6

src/main/java/seedu/address/ui/PersonDetailsPanel.java
Added a few helper methods so that the panel can be refreshed even when external classes want to use it Added about 30 LOC
=> Add a way to refresh UI

docs/DeveloperGuide.md, src/main/java/seedu/address/model/leave/Leave.java
=> Update use cases in DG

docs/UserGuide.md
Added warning boxes in UG
- warning added to clear command
- warning added to delete command
closes #131
=> Added warnings in UG

docs/DeveloperGuide.md
=> Fix DG manual testcases

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/model/leave/Leave.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Improve error message on delete and view command.
Mention that non-zero unsigned integer should not exceed MAX_INT which is 2147483647.
Update leave record error message.
=> Improve error message on delete and view command

docs/DeveloperGuide.md
Edit target user profile in DG.
=> Edit target user profile in DG
